### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by dannyfritz** [ekopelevich/prework_profile_site#1]
I love the playfulness of your site! :balloon: 

Lobster on the headers is what I thought was playful at first. Then I noticed the Q&A section. I'm glad you disassociated the dog and the blender :laughing:. But then I noticed the jumbotron changer movable circle. Dragged that guy around for a while.

I like the hover over pictures for all your hobbies. Awesome to see you have a design background. You'll find that skill is a super good way to differentiate among peers. :art: 

Awesome personal site. :+1:

**Comment by elanalynn** [comment]
Thanks for the feedback! Glad the moving button provided some entertainment. I was trying to figure out some way to give it more purpose... like make it a game somehow. Next time. :)
